MODULE_NAME = "eccc_datamart"
MODULE_DESCRIPTION = (
    "Environment and Climate Change Canada Data Catalogue file tree (tools prefixed "
    "eccc_datamart_), data-donnees.az.ec.gc.ca: browse folders (air, climate, ice, "
    "substances, water, species, sites, weather and others) with file sizes and modified "
    "dates; search the dataset folders by words (bilingual titles); describe a CSV or Excel "
    "file (sheets, header guess, columns, preview, read-me and data dictionary files in the "
    "same folder); read rows with column selection, exact filters, a text filter and paging "
    "(files up to 40 MB; ZIP archives, Word, PDF and images are listed but not opened). "
    "Convenience lookups: National Pollutant Release Inventory (NPRI) releases, disposals "
    "and transfers by facility for the single-year tables (2020 onward), and Greenhouse Gas "
    "Reporting Program (GHGRP) facility emissions by gas from 2004, filtered by facility, "
    "company, province, substance, NAICS and year. Covers NAPS air monitoring year folders "
    "from 1974, oil sands air, water and wildlife monitoring, and ECCC research data. Open "
    "Government Licence - Canada (commercial use allowed, attribution required). The "
    "folder and file endpoints are the ones the catalogue's own web page uses; they are "
    "undocumented. For weather, climate stations and hydrometric data use eccc_."
)
MODULE_DESCRIPTION_FR = (
    "Arborescence de fichiers du Catalogue de données d'Environnement et Changement "
    "climatique Canada (outils préfixés eccc_datamart_), data-donnees.az.ec.gc.ca : "
    "parcourir les dossiers (air, climat, glace, substances, eaux, espèces, sites, météo et "
    "autres) avec taille et date de modification des fichiers; rechercher les dossiers de "
    "données par mots (titres bilingues); décrire un fichier CSV ou Excel (feuilles, "
    "en-tête deviné, colonnes, aperçu, fichiers « Lisez-moi » et dictionnaires de données du "
    "même dossier); lire des lignes avec choix des colonnes, filtres exacts, filtre de texte "
    "et pagination (fichiers d'au plus 40 Mo; archives ZIP, Word, PDF et images listés mais "
    "non ouverts). Recherches directes : Inventaire national des rejets de polluants (INRP) "
    "par installation (tableaux annuels depuis 2020) et émissions des installations du "
    "Programme de déclaration des gaz à effet de serre (PDGES) par gaz depuis 2004, filtrées "
    "par installation, entreprise, province, substance, SCIAN et année. Couvre les dossiers "
    "annuels du SNPA depuis 1974, la surveillance des sables bitumineux et les données de "
    "recherche d'ECCC. Licence du gouvernement ouvert - Canada (usage commercial permis, "
    "mention de la source exigée). Les points d'accès des dossiers et des fichiers sont ceux "
    "de la page Web du catalogue; ils ne sont pas documentés. Pour la météo, les stations "
    "climatologiques et l'hydrométrie, voir eccc_."
)
