MODULE_NAME = "statcan"
MODULE_DESCRIPTION = (
    "Statistics Canada: the Web Data Service (WDS) for table/cube discovery, "
    "metadata and time-series data; the SDMX REST API for filtered, "
    "server-side-sliced series queries; Reference Data as a Service "
    "(RDaaS) for classifications, codesets, concordances, indices and "
    "exclusions (e.g. NAICS, the Standard Geographical Classification); and "
    "the 2021 Census Profile SDMX API (tools prefixed "
    "statcan_census_profile_) -- a separate host and dataflow structure "
    "from the WDS/SDMX table service above, covering demographic, dwelling, "
    "income, and other census characteristics by geography (province, "
    "census division/subdivision, census tract, dissemination area, "
    "forward sortation area, health/economic region, federal electoral "
    "district, population centre) -- search a geography or characteristic "
    "by name, then fetch values for any combination, including each "
    "characteristic's parent_code where the profile table itself nests "
    "one characteristic under another (e.g. age-group breakdowns). All "
    "tools accept lang: en|fr; the Census Profile API selects language "
    "via an Accept-Language header rather than a query parameter, "
    "handled internally. Earlier censuses (2001, 2006, 2011, 2016) have "
    "no equivalent live query API -- tools prefixed "
    "statcan_census_profile_archive_ resolve their official bulk "
    "CSV/TAB download links instead (1996 has no equivalent bulk-download "
    "page under this URL scheme and is not covered). The Daily's official "
    "Atom feeds (tools prefixed statcan_daily_): "
    "statcan_daily_get_releases returns StatCan's official release "
    "bulletin (new/updated tables, survey results, analytical products) "
    "for the last 100 days, either across all subjects or filtered to "
    "one of 30 (e.g. housing, labour, prices_and_price_indexes) -- The "
    "Daily's own web pages are plain server-rendered HTML with no JSON "
    "API, so this goes through StatCan's documented Atom feed family "
    "instead. statcan_daily_search_archive covers the full release "
    "history back to 2012-03-14 instead of the Atom feeds' 100-day "
    "window, via the JSON file backing the release-schedule calendar's "
    "client-side rendering (18,222 entries confirmed live) -- filter by "
    "title/reference-period keyword and/or a date range. StatCan's "
    '"Reference resources" catalogue (tools prefixed '
    "statcan_reference_): statcan_reference_search_documents searches "
    "2,031 definitions, data-source, and methodology documents -- "
    "distinct from actual data and from The Daily -- each carrying a "
    "catalogue number, category, description, and release date. Its "
    "search page silently ignores the keyword parameter (returning "
    "every document unfiltered) unless the session already visited the "
    "unparameterized base page first, confirmed live; handled "
    "internally with a one-time per-language warm-up request. The same "
    "tool family also covers StatCan's Analysis catalogue "
    "(statcan_reference_search_analysis, 10,841+ analytical articles, "
    '"Stats in brief", journals and periodicals) -- an identical '
    "Drupal search engine, path, and quirks, just a different catalogue. "
    "statcan_reference_get_document_formats resolves a catalogue number "
    "(from a search result, or any other tool) to its actual HTML/PDF "
    "download links; a series-level number instead returns its list of "
    "editions, each with its own catalogue number to resolve in turn -- "
    "the two page shapes look identical but are distinguished by the "
    "table's own header text. The same tool family also covers "
    "StatCan's Data catalogue (statcan_reference_search_data, "
    "13,342+ items) -- the same Drupal search engine again, and the "
    "only place with any discovery path at all for Public Use "
    "Microdata Files (PUMFs; e.g. catalogue number 71M0001X for the "
    "Labour Force Survey, 98M0001X for the Census) and other bulk data "
    "products WDS/SDMX cannot see. Most other Data-catalogue results "
    "are ordinary table PIDs also reachable via WDS/SDMX, so prefer "
    "those tools for routine table search. Confirmed live: a PUMF's "
    "catalogue-number page (via statcan_reference_get_document_formats) "
    "links one hop further to a bespoke, per-product static page (not "
    "this Drupal engine, so not parsed generically) listing the actual "
    "bulk download -- confirmed for 98M0001X, a direct, unauthenticated "
    "~173 MB ZIP with no login or account required. The 2016 Census "
    "Profile Web Data Service "
    "(tools prefixed "
    "statcan_census_profile_2016_): a genuinely separate, live JSON "
    "REST API (not SDMX) for 2016 census data -- distinct from "
    "statcan_census_profile_archive_* (2016 bulk downloads only). "
    "statcan_census_profile_2016_list_geographies finds a geography's "
    "DGUID; statcan_census_profile_2016_get_data fetches its full "
    "profile, optionally scoped to one of 14 topics, with separate "
    "total/male/female values and suppression symbols. StatCan's Delta "
    "File (tools prefixed statcan_delta_): statcan_delta_get_file_link "
    "resolves the daily bulk-update ZIP for one date (all table/vector "
    "data and metadata StatCan released that business day) and confirms "
    "it exists -- files only exist for business days with a release. "
    "StatCan's official Indicators feeds (tools prefixed "
    "statcan_indicators_): statcan_indicators_get_indicators returns "
    "current named-indicator values (population, CPI, GDP, trade, "
    'unemployment, etc., 2,362 confirmed live in the "all" dataset) '
    "with growth rates and a link back to the releasing Daily article -- "
    "the same feeds that power My StatCan and StatCan's own home page. "
    "StatCan's survey directory and IMDB metadata (tools prefixed "
    "statcan_surveys_): statcan_surveys_search_surveys searches the "
    "A-Z directory of ~899 surveys and statistical programs (active "
    "and inactive) to find a survey's numeric ID; "
    "statcan_surveys_get_survey_metadata fetches that survey's actual "
    '"Definitions, data sources and methods" content from IMDB '
    "(Integrated Metadata Base, a separate, older system from the "
    "Reference/Analysis catalogues) -- status, frequency, description, "
    "and subjects, with a detail_url to the full methodology sections "
    "(target population, sampling, data sources, data accuracy) rather "
    "than flattening that lengthy prose into fields. An unknown survey "
    "ID redirects through StatCan's own dedicated error page, which "
    "itself answers HTTP 500 due to a broken redirect chain on their "
    "end -- handled internally as a normal not-found result. StatCan's "
    "census-geography ArcGIS REST service (tools prefixed statcan_geo_, "
    "geo.statcan.gc.ca -- yet another host, and the only genuinely "
    "queryable geospatial API in this module, distinct from static "
    "bulk boundary-file downloads): statcan_geo_list_services finds "
    "what boundary products exist for a year (a census year like 2021 "
    "publishes a full suite covering every geography level; an "
    "intercensal year only CSD-level updates and the road network file "
    "-- genuinely different per year, discovered live rather than "
    "hardcoded); statcan_geo_get_layer_detail inspects one layer's "
    "field schema; statcan_geo_query_layer filters features by "
    "attribute (e.g. finding a CSD's DGUID by name) and, on request, "
    "returns polygon boundaries reprojected from the service's native "
    "EPSG:3347 (Statistics Canada Lambert) to plain lat/lon. Confirmed "
    "live: every error (an unknown year/service/layer, a malformed "
    "filter) comes back as HTTP 200 with an embedded error object, not "
    "a non-2xx status, and about one in three to five otherwise-valid "
    "requests hits a genuine transient HTTP 500 from an unhealthy "
    "backend node -- both handled internally (the latter by the "
    "existing shared retry layer). StatCan's Sustainable Development "
    "Goals Data Hub (tools prefixed statcan_sdg_, hosted as two "
    'separate static "Open SDG" GitHub Pages sites, not a StatCan-run '
    'API): statcan_sdg_search_indicators searches the "canada" '
    "framework (86 indicators, Canada's own national reporting) or "
    'the "global" framework (251 indicators, Canada\'s reporting '
    "against the UN's own Global Indicator Framework) -- distinct, "
    "differently-numbered indicator sets with no WDS/SDMX cube/PID "
    "equivalent. statcan_sdg_get_indicator_metadata returns an "
    "indicator's goal/target, description, units, and data sources; "
    "statcan_sdg_get_indicator_data returns its observations, each "
    "with whatever disaggregation columns (e.g. geography) that "
    "specific indicator happens to publish. The two frameworks use "
    "genuinely different metadata field names for the same concepts "
    "(confirmed live) -- handled internally so callers see one "
    "consistent shape regardless of framework."
)
MODULE_DESCRIPTION_FR = (
    "Statistique Canada : le Service de données Web (WDS) pour la "
    "découverte de tableaux/cubes, les métadonnées et les séries "
    "chronologiques; l'API REST SDMX pour des requêtes filtrées côté "
    "serveur; le service de données de référence (RDaaS) pour les "
    "classifications, ensembles de codes, concordances, index et "
    "exclusions (p. ex. le SCIAN, la Classification géographique type); "
    "et l'API SDMX du Profil du recensement de 2021 (outils préfixés "
    "statcan_census_profile_) -- un hôte et une structure de flux de "
    "données distincts du service de tableaux WDS/SDMX ci-dessus, "
    "couvrant les caractéristiques démographiques, de logement, de revenu "
    "et autres par géographie -- recherche d'une géographie ou d'une "
    "caractéristique par nom, puis récupération des valeurs pour toute "
    "combinaison, y compris le parent_code de chaque caractéristique "
    "lorsque le tableau de profil imbrique une caractéristique sous une "
    "autre (p. ex. les répartitions par groupe d'âge). Tous les outils "
    "acceptent lang : en|fr; l'API du Profil du recensement sélectionne "
    "la langue via l'en-tête Accept-Language plutôt qu'un paramètre de "
    "requête, géré en interne. Les recensements antérieurs (2001, 2006, "
    "2011, 2016) n'ont pas d'API de requête équivalente -- les outils "
    "préfixés statcan_census_profile_archive_ résolvent plutôt leurs "
    "liens de téléchargement en bloc officiels CSV/TAB (1996 n'a pas de "
    "page de téléchargement en bloc équivalente selon ce schéma d'URL et "
    "n'est pas couvert). Les flux Atom officiels du Quotidien (outils "
    "préfixés statcan_daily_) : statcan_daily_get_releases retourne le "
    "bulletin de diffusion officiel de Statistique Canada (tableaux "
    "nouveaux ou mis à jour, résultats d'enquêtes, produits analytiques) "
    "pour les 100 derniers jours, pour tous les sujets ou filtré à l'un "
    "des 30 sujets (p. ex. logement, travail, prix et indices des prix) "
    "-- les pages Web du Quotidien lui-même sont du HTML rendu côté "
    "serveur sans API JSON, donc ceci passe plutôt par la famille de "
    "flux Atom documentée de Statistique Canada. "
    "statcan_daily_search_archive couvre l'historique complet des "
    "diffusions depuis le 2012-03-14 plutôt que la fenêtre de 100 jours "
    "des flux Atom, via le fichier JSON qui alimente le rendu côté "
    "client du calendrier de diffusion (18 222 entrées confirmées en "
    "direct) -- filtrable par mot-clé du titre/de la période de "
    "référence et/ou par plage de dates. Le catalogue « Ressources de "
    "référence » de Statistique Canada (outils préfixés "
    "statcan_reference_) : statcan_reference_search_documents effectue "
    "une recherche parmi 2 031 documents de définitions, sources de "
    "données et méthodologie -- distincts des données proprement dites "
    "et du Quotidien -- chacun portant un numéro au catalogue, une "
    "catégorie, une description et une date de diffusion. Sa page de "
    "recherche ignore silencieusement le paramètre de mot-clé "
    "(retournant tous les documents sans filtre) à moins que la session "
    "n'ait déjà visité la page de base sans paramètre, confirmé en "
    "direct; géré en interne par une requête de préchauffage unique par "
    "langue. La même famille d'outils couvre aussi le catalogue Analyse "
    "de Statistique Canada (statcan_reference_search_analysis, plus de "
    "10 841 articles analytiques, « coups d'œil », revues et "
    "périodiques) -- le même moteur de recherche Drupal, les mêmes "
    "particularités, seul le catalogue diffère. "
    "statcan_reference_get_document_formats résout un numéro au "
    "catalogue (issu d'un résultat de recherche ou de tout autre outil) "
    "en ses véritables liens de téléchargement HTML/PDF; un numéro de "
    "niveau série retourne plutôt sa liste d'éditions, chacune avec son "
    "propre numéro au catalogue à résoudre à son tour -- les deux "
    "formes de page se ressemblent mais se distinguent par le texte "
    "d'en-tête du tableau. La même famille d'outils couvre aussi le "
    "catalogue Données de Statistique Canada "
    "(statcan_reference_search_data, plus de 13 342 éléments) -- le "
    "même moteur de recherche Drupal, et le seul point d'accès pour les "
    "fichiers de microdonnées à grande diffusion (FMGD; p. ex. numéro "
    "71M0001X pour l'Enquête sur la population active, 98M0001X pour le "
    "recensement) et d'autres produits de données en bloc que WDS/SDMX "
    "ne peuvent pas voir. La plupart des autres résultats de ce "
    "catalogue sont des PID de tableaux ordinaires aussi accessibles "
    "via WDS/SDMX; privilégier ces outils pour une recherche de tableau "
    "courante. Confirmé en direct : la page d'un FMGD (via "
    "statcan_reference_get_document_formats) mène un pas plus loin vers "
    "une page statique propre au produit (pas ce moteur Drupal, donc "
    "non analysée de façon générique) listant le véritable "
    "téléchargement en bloc -- confirmé pour 98M0001X, un fichier ZIP "
    "direct et non authentifié d'environ 173 Mo, sans connexion ni "
    "compte requis. Le service de données Web du Profil du "
    "recensement de 2016 (outils préfixés "
    "statcan_census_profile_2016_) : une API REST JSON véritablement "
    "distincte et en direct (pas du SDMX) pour les données du "
    "recensement de 2016 -- distincte de statcan_census_profile_archive_* "
    "(téléchargements en bloc de 2016 seulement). "
    "statcan_census_profile_2016_list_geographies trouve le DGUID d'une "
    "géographie; statcan_census_profile_2016_get_data récupère son "
    "profil complet, optionnellement limité à l'un de 14 sujets, avec "
    "des valeurs distinctes total/homme/femme et des symboles de "
    "suppression. Le fichier delta de Statistique Canada (outils "
    "préfixés statcan_delta_) : statcan_delta_get_file_link résout le "
    "lien de téléchargement du fichier ZIP de mise à jour quotidienne "
    "pour une date (toutes les données et métadonnées de tableaux/"
    "vecteurs diffusées ce jour ouvrable) et confirme son existence -- "
    "un fichier delta n'existe que pour les jours ouvrables ayant eu "
    "une diffusion. Les flux officiels d'indicateurs de Statistique "
    "Canada (outils préfixés statcan_indicators_) : "
    "statcan_indicators_get_indicators retourne les valeurs actuelles "
    "d'indicateurs nommés (population, IPC, PIB, commerce, chômage, "
    "etc., 2 362 confirmés en direct dans l'ensemble « all ») avec leur "
    "taux de croissance et un lien vers l'article du Quotidien qui les "
    "a diffusés -- les mêmes flux qui alimentent Mon StatCan et la page "
    "d'accueil de Statistique Canada. Le répertoire des enquêtes et les "
    "métadonnées de la BMDI de Statistique Canada (outils préfixés "
    "statcan_surveys_) : statcan_surveys_search_surveys recherche dans "
    "le répertoire alphabétique d'environ 899 enquêtes et programmes "
    "statistiques (actifs et inactifs) pour trouver l'identifiant "
    "numérique d'une enquête; statcan_surveys_get_survey_metadata "
    "récupère le véritable contenu « définitions, sources de données "
    "et méthodes » de cette enquête depuis la BMDI (Base de métadonnées "
    "intégrée, un système distinct et plus ancien que les catalogues "
    "Référence/Analyse) -- statut, fréquence, description et sujets, "
    "avec un detail_url vers les sections méthodologiques complètes "
    "plutôt que d'aplatir ce texte en champs. Un identifiant d'enquête "
    "inconnu redirige vers la page d'erreur dédiée de Statistique "
    "Canada, qui répond elle-même HTTP 500 en raison d'une chaîne de "
    "redirection brisée de leur côté -- géré en interne comme un "
    "résultat normal d'absence de résultat. Le service de géographie "
    "du recensement ArcGIS REST de Statistique Canada (outils préfixés "
    "statcan_geo_, geo.statcan.gc.ca -- encore un autre hôte, et la "
    "seule API géospatiale véritablement interrogeable de ce module, "
    "distincte des téléchargements en bloc de fichiers de limites "
    "statiques) : statcan_geo_list_services trouve les produits de "
    "limites disponibles pour une année (une année de recensement comme "
    "2021 publie un ensemble complet couvrant tous les niveaux de "
    "géographie; une année intercensitaire ne publie que des mises à "
    "jour au niveau des SDR et le fichier du réseau routier -- "
    "véritablement différent d'une année à l'autre, découvert en "
    "direct plutôt que codé en dur); statcan_geo_get_layer_detail "
    "inspecte le schéma des champs d'une couche; "
    "statcan_geo_query_layer filtre les entités par attribut (p. ex. "
    "trouver le DGUID d'une SDR par son nom) et, sur demande, retourne "
    "les limites polygonales reprojetées de la référence spatiale "
    "native du service (EPSG:3347, Lambert Statistique Canada) vers de "
    "simples coordonnées latitude/longitude. Confirmé en direct : "
    "chaque erreur (année/service/couche inconnu, filtre malformé) "
    "revient en HTTP 200 avec un objet d'erreur intégré, non un statut "
    "non-2xx, et environ une requête valide sur trois à cinq subit une "
    "véritable erreur HTTP 500 transitoire provenant d'un nœud "
    "défaillant -- les deux gérés en interne (la seconde par la couche "
    "de nouvelles tentatives déjà partagée). Le centre de données des "
    "objectifs de développement durable de Statistique Canada (outils "
    "préfixés statcan_sdg_, hébergé comme deux sites statiques « Open "
    "SDG » distincts sur GitHub Pages, non une API gérée par "
    "Statistique Canada) : statcan_sdg_search_indicators effectue une "
    "recherche dans le cadre « canada » (86 indicateurs, la "
    "déclaration nationale propre au Canada) ou le cadre « global » "
    "(251 indicateurs, la déclaration du Canada par rapport au cadre "
    "d'indicateurs mondial de l'ONU) -- des ensembles d'indicateurs "
    "distincts et numérotés différemment, sans équivalent de cube/PID "
    "WDS/SDMX. statcan_sdg_get_indicator_metadata retourne l'objectif "
    "et la cible d'un indicateur, sa description, ses unités et ses "
    "sources de données; statcan_sdg_get_indicator_data retourne ses "
    "observations, chacune avec les colonnes de désagrégation (p. ex. "
    "la géographie) que cet indicateur particulier publie. Les deux "
    "cadres utilisent des noms de champs de métadonnées véritablement "
    "différents pour les mêmes concepts (confirmé en direct) -- géré "
    "en interne afin que les appelants voient une forme cohérente peu "
    "importe le cadre."
)
