MODULE_NAME = "elections_provincial"
MODULE_DESCRIPTION = (
    "Provincial general election results by electoral district for Quebec, Alberta, "
    "British Columbia, Saskatchewan and Manitoba, tools prefixed elections_provincial_. "
    "Quebec: every candidate's votes and share by riding for the 14 general elections from "
    "1973 to 2022 (Elections Quebec open data). Alberta: votes by party in each electoral "
    "division, with the winning candidate's name, for the 2008 to 2023 general elections "
    "(Elections Alberta official results). British Columbia: every candidate's votes by "
    "electoral district for the 2005 to 2024 general elections, summed from the poll-level "
    "open data (Elections BC Open Data Licence). Saskatchewan: every candidate's votes by "
    "constituency for the 2011 to 2024 general elections, summed from Elections "
    "Saskatchewan's poll-by-poll files (the site states no terms or licence). Manitoba: every candidate's votes by electoral "
    "division, with registered voters, rejected ballots and turnout, for the seven general "
    "elections from 1999 to 2023, and poll-by-poll votes by voting area in one division "
    "(elections_provincial_get_voting_areas), from Elections Manitoba's downloads (the site "
    "states no terms or licence). Seats and "
    "votes by party are computed from the same rows and reconcile with the legislature "
    "(125, 87, 93, 61 and 57 seats in the latest elections). Ontario is not built: "
    "Elections Ontario's terms of use forbid scraping its results site. Federal results "
    "are in elections_results_."
)
MODULE_DESCRIPTION_FR = (
    "Résultats des élections générales provinciales par circonscription pour le Québec, "
    "l'Alberta, la Colombie-Britannique, la Saskatchewan et le Manitoba, outils préfixés "
    "elections_provincial_. Québec : votes et part des votes de chaque candidat par "
    "circonscription pour les 14 élections générales de 1973 à 2022 (données ouvertes "
    "d'Élections Québec). Alberta : votes par parti dans chaque division électorale, avec "
    "le nom du candidat élu, pour les élections générales de 2008 à 2023 (résultats "
    "officiels d'Elections Alberta). Colombie-Britannique : votes de chaque candidat par "
    "circonscription pour les élections générales de 2005 à 2024, additionnés à partir des "
    "données ouvertes par bureau de vote (licence de données ouvertes d'Elections BC). "
    "Saskatchewan : votes de chaque candidat par circonscription pour les élections "
    "générales de 2011 à 2024, additionnés à partir des fichiers par bureau de vote "
    "d'Elections Saskatchewan (le site n'énonce ni conditions ni licence : lecture aux "
    "risques du propriétaire du projet). Manitoba : votes de chaque candidat par division "
    "électorale, avec les électeurs inscrits, les bulletins rejetés et la participation, "
    "pour les sept élections générales de 1999 à 2023, et votes par section de vote dans "
    "une division (elections_provincial_get_voting_areas), d'après les téléchargements "
    "d'Élections Manitoba (le site n'énonce ni conditions ni licence : lecture aux risques "
    "du propriétaire du projet). Les sièges et les votes par parti sont calculés à partir "
    "des mêmes lignes et concordent avec la législature (125, 87, 93, 61 et 57 sièges aux "
    "dernières élections). L'Ontario n'est pas couvert : les conditions d'utilisation "
    "d'Elections Ontario interdisent le moissonnage de son site de résultats. Les "
    "résultats fédéraux sont dans elections_results_."
)
