MODULE_NAME = "elections_provincial"
MODULE_DESCRIPTION = (
    "Provincial general election results by electoral district for Quebec, Alberta and "
    "British Columbia, tools prefixed elections_provincial_. Quebec: every candidate's "
    "votes and share by riding for the 14 general elections from 1973 to 2022 (Elections "
    "Quebec open data). Alberta: votes by party in each electoral division, with the "
    "winning candidate's name, for the 2008 to 2023 general elections (Elections Alberta "
    "official results). British Columbia: every candidate's votes by electoral district for "
    "the 2005 to 2024 general elections, summed from the poll-level open data (Elections BC "
    "Open Data Licence). Seats and votes by party are computed from the same rows and "
    "reconcile with the legislature (125, 87 and 93 seats in the latest elections). Ontario "
    "is not built: Elections Ontario's terms of use forbid scraping its results site. "
    "Federal results are in elections_results_."
)
MODULE_DESCRIPTION_FR = (
    "Résultats des élections générales provinciales par circonscription pour le Québec, "
    "l'Alberta et la Colombie-Britannique, outils préfixés elections_provincial_. Québec : "
    "votes et part des votes de chaque candidat par circonscription pour les 14 élections "
    "générales de 1973 à 2022 (données ouvertes d'Élections Québec). Alberta : votes par "
    "parti dans chaque division électorale, avec le nom du candidat élu, pour les élections "
    "générales de 2008 à 2023 (résultats officiels d'Elections Alberta). Colombie-Britannique "
    ": votes de chaque candidat par circonscription pour les élections générales de 2005 à "
    "2024, additionnés à partir des données ouvertes par bureau de vote (licence de données "
    "ouvertes d'Elections BC). Les sièges et les votes par parti sont calculés à partir des "
    "mêmes lignes et concordent avec la législature (125, 87 et 93 sièges aux dernières "
    "élections). L'Ontario n'est pas couvert : les conditions d'utilisation d'Elections "
    "Ontario interdisent le moissonnage de son site de résultats. Les résultats fédéraux "
    "sont dans elections_results_."
)
