MODULE_NAME = "ised"
MODULE_DESCRIPTION = (
    "Innovation, Science and Economic Development Canada (ISED), via four separate "
    "platforms. Corporations Canada's federal corporation lookup API "
    "(ised-isde.canada.ca/cc/lgcy/api/corporations, tools prefixed ised_corporations_): "
    "look up one federal corporation by its numeric corporation ID or 9-digit business "
    "number, returning current status, names, addresses, director limits, annual "
    "return filing history, and incorporation/by-law activities. The Spectrum "
    "Management System's licence site data (an Esri-hosted ArcGIS FeatureServer, tools "
    "prefixed ised_spectrum_): ~840,000 wireless spectrum licence site records "
    "(licensee, service type, transmit/receive frequencies, tower location and height, "
    "antenna specifications), refreshed monthly by ISED. The Canadian Trademarks "
    "Database (CIPO)'s search API (ised-isde.canada.ca/cipo/trademark-search/srch, "
    "tools prefixed ised_cipo_): search over 2 million Canadian trademark records "
    "(registered, pending, expunged, or abandoned) by owner name, mark text, "
    "goods/services text, application/registration number, Nice classification, or "
    "Vienna design code, returning mark name/type, status, Nice classes, and logo "
    "image URLs. CIPO's IP Horizons researcher datasets (tools prefixed "
    "ised_ip_horizons_): the quarterly bulk files of the full patent, industrial "
    "design and trademark registers, listed by table, patent-number range and "
    "release from their open.canada.ca packages, plus the patent and industrial "
    "design data dictionaries (bilingual variable names, types and descriptions), "
    "and patent lookup by number or search by owner/inventor name, IPC class, title "
    "and filing date over the patent main, party and IPC tables, downloaded on "
    "first use into a local Parquet cache (MAPLE_IP_HORIZONS_CACHE_DIR). "
    "The Trademarks Database endpoint is not documented publicly -- it backs the search "
    "UI's own XHR calls -- but is a plain unauthenticated JSON POST with no session "
    "requirement, confirmed live. It has no pagination beyond the requested "
    "max_return count. The Clean Growth Hub's federal clean technology investment "
    "figures for 2016-2024 (tools prefixed ised_clean_growth_), published only as a "
    "web page and PDF, read into numbers: headline totals, value by year and "
    "subsector, and share of agreements by province. ISED's bulk statistical datasets (Financial Performance "
    "Data, historical insolvency statistics, and a bulk CSV export of the same "
    "federal-corporations register) are ordinary CKAN datasets published by the "
    "'ic' organization on open.canada.ca, already reachable via "
    "ckan_search_datasets(fq='organization:ic') on the federal CKAN module -- no "
    "dedicated module needed for those."
)
MODULE_DESCRIPTION_FR = (
    "Innovation, Sciences et Développement économique Canada (ISDE), via quatre "
    "plateformes distinctes. L'API de recherche de sociétés fédérales de "
    "Corporations Canada (ised-isde.canada.ca/cc/lgcy/api/corporations, outils "
    "préfixés ised_corporations_) : recherche d'une société fédérale "
    "par son numéro de société ou son numéro d'entreprise à 9 chiffres, "
    "retournant le statut actuel, les dénominations, les adresses, les limites du "
    "nombre d'administrateurs, l'historique des rapports annuels et les activités "
    "de constitution et règlements administratifs. Les données sur les sites de licences de "
    "spectre du Système de gestion du spectre (un FeatureServer ArcGIS hébergé "
    "par Esri, outils préfixés ised_spectrum_) : environ 840 000 enregistrements "
    "de sites de licences de spectre sans fil, mis à jour mensuellement par ISDE. "
    "L'API de recherche de la Base de données sur les marques de commerce "
    "canadiennes (OPIC) (ised-isde.canada.ca/cipo/trademark-search/srch, outils "
    "préfixés ised_cipo_) : recherche parmi plus de 2 millions de marques de "
    "commerce canadiennes par nom de propriétaire, texte de la marque, biens/"
    "services, numéro de demande/enregistrement, classification de Nice ou code "
    "de Vienne, retournant le nom et le type de la marque, le statut, les classes "
    "de Nice et les URL des images de logo. Les jeux de données Horizons PI de "
    "l'OPIC (outils préfixés ised_ip_horizons_) : les fichiers en vrac "
    "trimestriels des registres complets des brevets, dessins industriels et "
    "marques de commerce, par table, plage de numéros et diffusion, ainsi que "
    "les dictionnaires de données des brevets et des dessins industriels, "
    "et la recherche de brevets par numéro, titulaire, inventeur, classe CIB, titre "
    "ou date de dépôt (tables téléchargées à la première utilisation). "
    "Ce point de terminaison n'est pas "
    "documenté publiquement, mais il s'agit d'une simple requête POST JSON non "
    "authentifiée, confirmée en direct, sans pagination au-delà du nombre "
    "maximal demandé. Les jeux de données statistiques en vrac d'ISDE sont déjà "
    "accessibles via le module CKAN fédéral -- aucun module dédié n'est "
    "nécessaire pour ceux-ci."
)
