MODULE_NAME = "statcan"
MODULE_DESCRIPTION = (
    "Statistics Canada: the Web Data Service (WDS) for table/cube discovery, "
    "metadata and time-series data; the SDMX REST API for filtered, "
    "server-side-sliced series queries; Reference Data as a Service "
    "(RDaaS) for classifications, codesets, concordances, indices and "
    "exclusions (e.g. NAICS, the Standard Geographical Classification); and "
    "the 2021 Census Profile SDMX API (tools prefixed "
    "statcan_census_profile_) -- a separate host and dataflow structure "
    "from the WDS/SDMX table service above, covering demographic, dwelling, "
    "income, and other census characteristics by geography (province, "
    "census division/subdivision, census tract, dissemination area, "
    "forward sortation area, health/economic region, federal electoral "
    "district, population centre) -- search a geography or characteristic "
    "by name, then fetch values for any combination. All tools accept "
    "lang: en|fr; the Census Profile API selects language via an "
    "Accept-Language header rather than a query parameter, handled "
    "internally."
)
MODULE_DESCRIPTION_FR = (
    "Statistique Canada : le Service de données Web (WDS) pour la "
    "découverte de tableaux/cubes, les métadonnées et les séries "
    "chronologiques; l'API REST SDMX pour des requêtes filtrées côté "
    "serveur; le service de données de référence (RDaaS) pour les "
    "classifications, ensembles de codes, concordances, index et "
    "exclusions (p. ex. le SCIAN, la Classification géographique type); "
    "et l'API SDMX du Profil du recensement de 2021 (outils préfixés "
    "statcan_census_profile_) -- un hôte et une structure de flux de "
    "données distincts du service de tableaux WDS/SDMX ci-dessus, "
    "couvrant les caractéristiques démographiques, de logement, de revenu "
    "et autres par géographie -- recherche d'une géographie ou d'une "
    "caractéristique par nom, puis récupération des valeurs pour toute "
    "combinaison. Tous les outils acceptent lang : en|fr; l'API du "
    "Profil du recensement sélectionne la langue via l'en-tête "
    "Accept-Language plutôt qu'un paramètre de requête, géré en "
    "interne."
)
