MODULE_NAME = "statcan"
MODULE_DESCRIPTION = (
    "Statistics Canada: the Web Data Service (WDS) for table/cube discovery, "
    "metadata and time-series data; the SDMX REST API for filtered, "
    "server-side-sliced series queries; Reference Data as a Service "
    "(RDaaS) for classifications, codesets, concordances, indices and "
    "exclusions (e.g. NAICS, the Standard Geographical Classification); and "
    "the 2021 Census Profile SDMX API (tools prefixed "
    "statcan_census_profile_) -- a separate host and dataflow structure "
    "from the WDS/SDMX table service above, covering demographic, dwelling, "
    "income, and other census characteristics by geography (province, "
    "census division/subdivision, census tract, dissemination area, "
    "forward sortation area, health/economic region, federal electoral "
    "district, population centre) -- search a geography or characteristic "
    "by name, then fetch values for any combination, including each "
    "characteristic's parent_code where the profile table itself nests "
    "one characteristic under another (e.g. age-group breakdowns). All "
    "tools accept lang: en|fr; the Census Profile API selects language "
    "via an Accept-Language header rather than a query parameter, "
    "handled internally. Earlier censuses (2001, 2006, 2011, 2016) have "
    "no equivalent live query API -- tools prefixed "
    "statcan_census_profile_archive_ resolve their official bulk "
    "CSV/TAB download links instead (1996 has no equivalent bulk-download "
    "page under this URL scheme and is not covered). The Daily's official "
    "Atom feeds (tools prefixed statcan_daily_): "
    "statcan_daily_get_releases returns StatCan's official release "
    "bulletin (new/updated tables, survey results, analytical products) "
    "for the last 100 days, either across all subjects or filtered to "
    "one of 30 (e.g. housing, labour, prices_and_price_indexes) -- The "
    "Daily's own web pages are plain server-rendered HTML with no JSON "
    "API, so this goes through StatCan's documented Atom feed family "
    "instead."
)
MODULE_DESCRIPTION_FR = (
    "Statistique Canada : le Service de données Web (WDS) pour la "
    "découverte de tableaux/cubes, les métadonnées et les séries "
    "chronologiques; l'API REST SDMX pour des requêtes filtrées côté "
    "serveur; le service de données de référence (RDaaS) pour les "
    "classifications, ensembles de codes, concordances, index et "
    "exclusions (p. ex. le SCIAN, la Classification géographique type); "
    "et l'API SDMX du Profil du recensement de 2021 (outils préfixés "
    "statcan_census_profile_) -- un hôte et une structure de flux de "
    "données distincts du service de tableaux WDS/SDMX ci-dessus, "
    "couvrant les caractéristiques démographiques, de logement, de revenu "
    "et autres par géographie -- recherche d'une géographie ou d'une "
    "caractéristique par nom, puis récupération des valeurs pour toute "
    "combinaison, y compris le parent_code de chaque caractéristique "
    "lorsque le tableau de profil imbrique une caractéristique sous une "
    "autre (p. ex. les répartitions par groupe d'âge). Tous les outils "
    "acceptent lang : en|fr; l'API du Profil du recensement sélectionne "
    "la langue via l'en-tête Accept-Language plutôt qu'un paramètre de "
    "requête, géré en interne. Les recensements antérieurs (2001, 2006, "
    "2011, 2016) n'ont pas d'API de requête équivalente -- les outils "
    "préfixés statcan_census_profile_archive_ résolvent plutôt leurs "
    "liens de téléchargement en bloc officiels CSV/TAB (1996 n'a pas de "
    "page de téléchargement en bloc équivalente selon ce schéma d'URL et "
    "n'est pas couvert). Les flux Atom officiels du Quotidien (outils "
    "préfixés statcan_daily_) : statcan_daily_get_releases retourne le "
    "bulletin de diffusion officiel de Statistique Canada (tableaux "
    "nouveaux ou mis à jour, résultats d'enquêtes, produits analytiques) "
    "pour les 100 derniers jours, pour tous les sujets ou filtré à l'un "
    "des 30 sujets (p. ex. logement, travail, prix et indices des prix) "
    "-- les pages Web du Quotidien lui-même sont du HTML rendu côté "
    "serveur sans API JSON, donc ceci passe plutôt par la famille de "
    "flux Atom documentée de Statistique Canada."
)
