MODULE_NAME = "cmhc"
MODULE_DESCRIPTION = (
    "Canada Mortgage and Housing Corporation (CMHC), via two separate "
    "platforms. The Housing Market Information Portal (HMIP, "
    "www03.cmhc-schl.gc.ca/hmip-pimh, tools prefixed cmhc_): rental "
    "market survey vacancy rates and rents, new housing construction "
    "(starts/completions), secondary rental market, seniors' rental "
    "housing, and population/household/core-housing-need indicators, "
    "for Canada and by province, as historical time series or a "
    "current cross-tabulation -- no hardcoded table catalogue, "
    "categories and breakdowns are discovered live and data is fetched "
    "through HMIP's own CSV export. The 'Data Tables' document "
    "catalogue (www.cmhc-schl.gc.ca, tools prefixed cmhc_dt_): official "
    "per-edition Excel table publications for Rental Market Survey, "
    "Household Characteristics, and related surveys, with direct "
    "download links resolved through the site's own resolver API for "
    "any historical geography/edition, not just the current one."
)
MODULE_DESCRIPTION_FR = (
    "Société canadienne d'hypothèques et de logement (SCHL), via deux "
    "plateformes distinctes. Le Portail d'information sur le marché du "
    "logement (PIMH, www03.cmhc-schl.gc.ca/hmip-pimh, outils préfixés "
    "cmhc_) : taux d'inoccupation et loyers de l'Enquête sur les "
    "logements locatifs, mises en chantier et achèvements de nouveaux "
    "logements, marché locatif secondaire, logements locatifs pour "
    "personnes âgées, et indicateurs sur la population, les ménages et "
    "les besoins impérieux en matière de logement, pour le Canada et "
    "par province, sous forme de série chronologique ou de tableau "
    "croisé actuel -- aucun catalogue codé en dur, les catégories et "
    "répartitions sont découvertes en direct et les données récupérées "
    "via l'export CSV officiel du PIMH. Le catalogue de documents "
    "« Tableaux de données » (www.cmhc-schl.gc.ca, outils préfixés "
    "cmhc_dt_) : publications officielles de tableaux Excel par "
    "édition pour l'Enquête sur les logements locatifs, les "
    "caractéristiques des ménages et d'autres enquêtes connexes, avec "
    "des liens de téléchargement directs résolus via l'API de "
    "résolution propre au site, pour n'importe quelle géographie ou "
    "édition historique, pas seulement l'actuelle."
)
