"""Constants for the City of Lethbridge's ArcGIS Hub deployment."""

DOMAIN = "opendata.lethbridge.ca"
RATE_LIMIT_SOURCE = "arcgis-lethbridge"
RATE_LIMIT_PER_SECOND = 2.0
RATE_LIMIT_CAPACITY = 5.0

CACHE_TTL_SEARCH_SECONDS = 10 * 60
CACHE_TTL_ITEM_SECONDS = 60 * 60
CACHE_TTL_ROWS_SECONDS = 5 * 60

SEARCH_LIMIT_DEFAULT = 10
SEARCH_LIMIT_MAX = 100
ROWS_LIMIT_DEFAULT = 10
ROWS_LIMIT_MAX = 1000
DESCRIPTION_EXCERPT_LENGTH = 300

LANDING_PAGE_URL = f"https://{DOMAIN}/datasets/"
