MODULE_NAME = "ised"
MODULE_DESCRIPTION = (
    "Innovation, Science and Economic Development Canada (ISED), via two separate "
    "platforms. Corporations Canada's federal corporation lookup API "
    "(ised-isde.canada.ca/cc/lgcy/api/corporations, tools prefixed ised_corporations_): "
    "look up one federal corporation by its numeric corporation ID or 9-digit business "
    "number, returning current status, names, addresses, director limits, annual "
    "return filing history, and incorporation/by-law activities. The Spectrum "
    "Management System's licence site data (an Esri-hosted ArcGIS FeatureServer, tools "
    "prefixed ised_spectrum_): ~840,000 wireless spectrum licence site records "
    "(licensee, service type, transmit/receive frequencies, tower location and height, "
    "antenna specifications), refreshed monthly by ISED. ISED's bulk statistical "
    "datasets (Financial Performance Data, historical insolvency statistics, and a "
    "bulk CSV export of the same federal-corporations register) are ordinary CKAN "
    "datasets published by the 'ic' organization on open.canada.ca, already reachable "
    "via ckan_search_datasets(fq='organization:ic') on the federal CKAN module -- no "
    "dedicated module needed for those."
)
MODULE_DESCRIPTION_FR = (
    "Innovation, Sciences et Développement économique Canada (ISDE), via deux "
    "plateformes distinctes. L'API de recherche de sociétés fédérales de "
    "Corporations Canada (ised-isde.canada.ca/cc/lgcy/api/corporations, outils "
    "préfixés ised_corporations_) : recherche d'une société fédérale "
    "par son numéro de société ou son numéro d'entreprise à 9 chiffres, "
    "retournant le statut actuel, les dénominations, les adresses, les limites du "
    "nombre d'administrateurs, l'historique des rapports annuels et les activités "
    "d'incorporation/règlements. Les données sur les sites de licences de "
    "spectre du Système de gestion du spectre (un FeatureServer ArcGIS hébergé "
    "par Esri, outils préfixés ised_spectrum_) : environ 840 000 enregistrements "
    "de sites de licences de spectre sans fil, mis à jour mensuellement par ISDE. "
    "Les jeux de données statistiques en vrac d'ISDE sont déjà accessibles via "
    "le module CKAN fédéral -- aucun module dédié n'est nécessaire pour "
    "ceux-ci."
)
