MODULE_NAME = "ab_opendata"
MODULE_DESCRIPTION = (
    "Open Alberta file reader (tools prefixed ab_opendata_): the Excel and CSV files "
    "published on open.alberta.ca, whose DataStore has no active resources, so the files "
    "are the only route to the numbers. Search the portal's open datasets that have "
    ".xlsx, .xls or .csv files (filters: organization, text, format) with title, "
    "ministry, licence, resources with format and size, and last-modified date; list the "
    "organizations; describe a file's sheets and columns; read a file with column "
    "selection, exact filters, a text filter, a guessed (or given) header row and paging. "
    "Covers Alberta Health indicator tables, Treasury Board and Finance (economic "
    "review, indicators at a glance, population projections), Education results, "
    "Assisted Living and Social Services caseloads (AISH, Income Support), Municipal "
    "Affairs financial returns, energy royalties, traffic volumes and collisions, vital "
    "statistics, post-secondary data. Nearly every dataset is under the Open Government "
    "Licence - Alberta (commercial use allowed with attribution); a dataset under any "
    "other licence is flagged. Discovery uses the portal's CKAN API and file reads wait "
    "10 seconds between requests. Use ckan_ with "
    "portal=ab for the rest of the catalogue (resources that are links, maps, PDFs)."
)
MODULE_DESCRIPTION_FR = (
    "Lecteur de fichiers d'Open Alberta (outils préfixés ab_opendata_) : les fichiers "
    "Excel et CSV publiés sur open.alberta.ca, dont le DataStore n'a aucune ressource "
    "active, de sorte que les fichiers sont le seul accès aux chiffres. Recherche des "
    "jeux de données ouverts de l'Alberta ayant des fichiers .xlsx, .xls ou .csv (filtres "
    ": organisation, texte, format) avec titre, ministère, licence, ressources (format et "
    "taille) et date de dernière modification ; liste des organisations ; description des "
    "feuilles et des colonnes d'un fichier ; lecture d'un fichier avec choix des colonnes, "
    "filtres exacts, filtre de texte, ligne d'en-tête devinée (ou donnée) et pagination. "
    "Couvre les tableaux d'indicateurs d'Alberta Health, le Conseil du Trésor et les "
    "Finances (revue économique, indicateurs en bref, projections de population), les "
    "résultats en éducation, les dossiers de l'AISH et du soutien du revenu, les "
    "déclarations financières municipales, les redevances énergétiques, les volumes de "
    "circulation et les collisions, les statistiques de l'état civil et les données "
    "postsecondaires. Presque tous les jeux relèvent de la Licence du gouvernement ouvert "
    "– Alberta (usage commercial permis avec mention de la source) ; un jeu sous une autre "
    "licence est signalé. La découverte passe par l'API CKAN du portail et les lectures de "
    "fichiers attendent 10 secondes entre deux requêtes. Voir ckan_ avec portal=ab "
    "pour le reste du catalogue."
)
