MODULE_NAME = "cdc"
MODULE_DESCRIPTION = (
    "Canadian Dairy Commission (cdc-ccl.ca), tools prefixed cdc_: special milk class "
    "component prices ($/kg butterfat, protein, other solids for classes 3(d), 4(a), "
    "4(m), 5(a), 5(b), 5(c), monthly since 2002, from the CDC's yearly CSV files), the "
    "butter support price since 2010, the national milk production target (total "
    "quota, kg butterfat, monthly since 2017), the Harmonized Milk Classification "
    "System, and the CDC market data file on AAFC's open-data server (farm milk "
    "production by province since 2016, milk class sales in litres, kg and dollars for "
    "the ten provinces and East/West regions since July 2020, farms shipping milk). "
    "cdc_list_datasets also lists the provincial milk marketing boards and national "
    "poultry and egg agencies checked on 2026-09-26: their data are PDFs (Dairy Farmers "
    "of Ontario, Les Producteurs de lait du Quebec, Alberta Milk, Chicken and Turkey "
    "Farmers of Canada), behind a captcha or broken TLS (BC Milk Marketing Board, "
    "Canadian Hatching Egg Producers), or limited by terms (Egg Farmers of Canada), "
    "with StatCan tables (wds_) and CKAN tariff-rate-quota lists as alternatives."
)
MODULE_DESCRIPTION_FR = (
    "Commission canadienne du lait (cdc-ccl.ca), outils préfixés cdc_ : prix des "
    "composants du lait des classes spéciales ($/kg de matière grasse, protéines et "
    "autres solides pour les classes 3(d), 4(a), 4(m), 5(a), 5(b), 5(c), mensuels "
    "depuis 2002), prix de soutien du beurre depuis 2010, cible nationale de production "
    "laitière (quota total en kg de matière grasse, mensuel depuis 2017), Système "
    "harmonisé de classification du lait, et fichier de données de marché de la CCL "
    "(production de lait par province depuis 2016, ventes par classe en litres, kg et "
    "dollars pour les dix provinces et les régions Est et Ouest depuis juillet 2020, "
    "fermes expédiant du lait). cdc_list_datasets indique aussi les offices de "
    "commercialisation provinciaux et les agences nationales de la volaille et des "
    "œufs vérifiés le 2026-09-26, dont les données sont en PDF, bloquées ou limitées "
    "par leurs conditions, avec les tableaux de StatCan (wds_) comme solution de rechange."
)
